advisor/urls.py
from django.urls import path
from .views import advisor_view, course_offer_view, register_view

app_name = 'advisor'

urlpatterns = [

    path('', advisor_view, name='advisor-view'),
    path('advisor/course-offer', course_offer_view, name='advisor-course-offer'),
    path('advisor/course-offer/course-register', register_view, name='advisor-course-register')

]

pre_registration/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from accounts.views import portal, students, advisors

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', portal.home, name='home'),

    path('admin-panel/', include('admin_panel.urls')),

    path('advisor/', include('advisor.urls')),

    path('student/', include('student.urls')),

    path('accounts/signup/', portal.SignUpView.as_view(), name='signup'),

    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),

    path('accounts/signup/advisor/', advisors.AdvisorSignUpView.as_view(), name='advisor_signup'),

    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),

    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view(), name='logout'),

    re_path(r'^accounts/reset/$',
            auth_views.PasswordResetView.as_view(
                template_name='password_reset.html',
                email_template_name='password_reset_email.html',
                subject_template_name='password_reset_subject.txt'
            ),
            name='password_reset'),
    re_path(r'^accounts/reset/done/$',
            auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
            name='password_reset_done'),
    re_path(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
            name='password_reset_confirm'),
    re_path(r'^accounts/reset/complete/$',
            auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
            name='password_reset_complete'),

    re_path(r'^accounts/settings/password/$',
            auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
            name='password_change'),

    re_path(r'^accounts/settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='password_change_done.html'),
            name='password_change_done'),

]

advisor/models.py
from django.db import models

# Create your models here.

advisor/forms.py
from django import forms

accounts/views/advisors.py
from accounts.forms import AdvisorSignUpForm
from accounts.models import User
from django.contrib.auth import login
from django.shortcuts import redirect
from django.views.generic import CreateView


class AdvisorSignUpView(CreateView):
    model = User
    form_class = AdvisorSignUpForm
    template_name = 'signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Teacher '
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')

advisor/views.py
from accounts.models import User, Advisor
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.db.models import Sum
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse
from admin_panel.models import StudentsAdvisorModel, CourseOfferModel, CourseListModel
# Create your views here.
from student.decorators import advisor_required
from student.models import StudentCourseList


@login_required
@advisor_required
def advisor_view(request):

    qs = StudentsAdvisorModel.objects.filter(advisor=request.user.id)

    queryset = {
        'students': qs
    }

    return render(request, 'advisor.html', queryset)


@login_required
@advisor_required
def course_offer_view(request):
    query = CourseListModel.objects.all()

    q = request.POST.get('q1')

    semester = request.POST.get('q2')

    course = CourseOfferModel.objects.filter(semester__semester__iexact=semester, section__iexact='A').all()

    query1 = CourseListModel.objects.search(q)

    context = {
        'search': query,
        'search1': query1,
        'semester': course,
    }

    return render(request, 'advisor-course-offer-list.html', context)


@login_required
@advisor_required
def register_view(request):
    q = request.POST.get('q')

    b = Advisor.objects.get(user__username=request.user)

    q2 = StudentsAdvisorModel.objects.filter(advisor=b).all()

    query1 = CourseOfferModel.objects.search(q)

    if request.is_ajax():

        course_name = request.GET.get('course_name', False)
        section = request.GET.get('section', False)
        credit = request.GET.get('course_credit', False)
        student = request.GET.get('student', False)

        a = CourseOfferModel.objects.get(course__course_name__iexact=course_name, section__iexact=section)
        d = CourseOfferModel.objects.get(id=a.id)

        enrolled_student = a.enrolled_students
        C = a.course.course_name

        exist_course = StudentCourseList.objects.filter(user__username=student, course__course__course_name=C).exists()

        c_credit = StudentCourseList.objects.filter(user__username=student).aggregate(
            credit=Sum('course__course__course_credit'))

        c_course = StudentCourseList.objects.filter(user__username=student).count()
        print(c_course)

        if c_credit['credit'] is None:
            course_credit = 0 + int(credit)

        else:
            course_credit = c_credit['credit'] + int(credit)

        f = False

        s = User.objects.filter(username=student)
        student = User.objects.get(id=s[0].id)

        if not exist_course and course_credit <= 18 and enrolled_student < 40:

            c = StudentCourseList(user=student, course=d)
            c.save()
            d.enrolled_students = enrolled_student + 1
            d.save()
            f = True

            student_advisor = StudentsAdvisorModel.objects.get(student__user__username=student)
            student_advisor1 = StudentsAdvisorModel.objects.get(id=student_advisor.id)

            student_advisor1.number_of_course_taken = c_course + 1
            student_advisor1.total_credit_taken = course_credit
            student_advisor1.save()

        data = {
            'is_taken': exist_course,
            'is_save': f,
            'credit': course_credit > 18,
            'enrolled_student': enrolled_student >= 40,
        }
        return JsonResponse(data)

    context = {
        'course': query1,
        'student': q2,
    }

    return render(request, 'advisor-course-register.html', context)

advisor/templates/advisor-course-offer-list.html
{% extends 'index.html' %}

{% load static %}

{% load humanize %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'advisor:advisor-view' %}">Advisor Portal</a></li>
    <li class="breadcrumb-item active">Course Offer</li>
{% endblock %}

{% block content %}
        <div style="width: 100%">
            <div style="width: 25%; float: left">

                <form class="form-group" action="{% url 'advisor:advisor-course-offer' %}" method="post">{% csrf_token %}

                    <label class="form-group">Semester</label>

                    <select class="form-group" id="semester" name="q2">
                                <option class="form-group" selected>Choose</option>
                                <option class="form-group" value="L1T1">Level1 Term1</option>
                                <option class="form-group" value="L1T2">Level1 Term2</option>
                                <option class="form-group" value="L1T3">Level1 Term3</option>
                                <option class="form-group" value="L2T1">Level2 Term1</option>
                                <option class="form-group" value="L2T2">Level2 Term2</option>
                                <option class="form-group" value="L2T3">Level2 Term3</option>
                                <option class="form-group" value="L3T1">Level3 Term1</option>
                                <option class="form-group" value="L3T2">Level3 Term2</option>
                                <option class="form-group" value="L3T3">Level3 Term3</option>
                                <option class="form-group" value="L4T1">Level4 Term1</option>
                                <option class="form-group" value="L4T2">Level4 Term2</option>
                                <option class="form-group" value="L4T3">Level4 Term3</option>
                    </select>
                    <button type="submit" class="btn btn-outline-success">Get List</button>

                </form>
            </div>

            <div style="width: 25%;float: right">
                <form class="form" action="{% url 'advisor:advisor-course-offer' %}" method="post">{% csrf_token %}
                    <input type="text" placeholder="Search Course Code..." name="q1" value=""
                           style=" border: 1px; margin-top: 1px; height: 35px; width: 200px">

                    <button type="submit" class="btn btn-outline-success">Search</button>
                </form>
            </div>
        </div>

<div class="clearfix"></div>

    {% if semester.exists %}

        <table id="example3" class="table table-striped mb-4" style="margin-top: 22px">

            <thead class="table-inverse">
                <tr>
                    <th>Course Code</th>
                    <th>Course Name</th>
                    <th>Course Credit</th>
                </tr>
            </thead>
            <tbody>
            {% for c in semester %}
                <tr>
                    <form action="{% url 'advisor:advisor-course-register' %}" method="post">{% csrf_token %}
                        <td class="align-middle">
                            <button type="submit" class="btn btn-outline-success" name="q" value="{{ c.course.course_code }}"
                                    style="margin-left: 50px">{{ c.course.course_code }}</button>
                        </td>
                    </form>
                    <td class="align-middle">{{ c.course.course_name }}</td>
                    <td class="align-middle">{{ c.course.course_credit }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% elif search1.exists %}

        <table id="example2" class="table table-striped mb-4" style="margin-top: 22px">

            <thead class="table-inverse">
                <tr>
                    <th>Course Code</th>
                    <th>Course Name</th>
                    <th>Course Credit</th>
                </tr>
            </thead>
            <tbody>
            {% for c in search1 %}
                <tr>
                    <form action="{% url 'advisor:advisor-course-register' %}" method="post">{% csrf_token %}
                        <td class="align-middle">
                            <button type="submit" class="btn btn-outline-success" name="q" value="{{ c.course_code }}"
                                    style="margin-left: 50px">{{ c.course_code }}</button>
                        </td>
                    </form>
                    <td class="align-middle">{{ c.course_name }}</td>
                    <td class="align-middle">{{ c.course_credit }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% elif search.exists %}

        <table id="example2" class="table table-striped mb-4" style="margin-top: 22px">

            <thead class="table-inverse">
                <tr>
                    <th>Course Code</th>
                    <th>Course Name</th>
                    <th>Course Credit</th>
                </tr>
            </thead>
            <tbody>
            {% for c in search %}
                <tr>
                    <form action="{% url 'advisor:advisor-course-register' %}" method="post">{% csrf_token %}
                        <td class="align-middle">
                            <button type="submit" class="btn btn-outline-success" name="q" value="{{ c.course_code }}"
                                    style="margin-left: 50px">{{ c.course_code }}</button>
                        </td>
                    </form>
                    <td class="align-middle">{{ c.course_name }}</td>
                    <td class="align-middle">{{ c.course_credit }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% endif %}

{% endblock content %}

advisor/templates/advisor-course-register.html
{% extends 'index.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'advisor:advisor-view' %}">Advisor Portal</a></li>
    <li class="breadcrumb-item"><a href="{% url 'advisor:advisor-course-offer' %}">Course Offer</a></li>
    <li class="breadcrumb-item active">Register Course</li>
{% endblock %}

{% block content %}

    <div class="dropdown">

        <label>Select Student ID</label>

        <select id="student">
                <option value="none" selected>--------------</option>
                {% for s in student %}
                    <option value="{{ s.student.user.username }}">{{ s.student.user.username }}</option>
                {% endfor %}
        </select>

    </div>

    {% if course.exists %}

        <table id="myTable" class="table table-striped mb-4" style="margin-top: 22px">

            <thead class="table-inverse">
                <tr>
                    <th>Season</th>
                    <th>Year</th>
                    <th>Semester</th>
                    <th>Course Code</th>
                    <th>Course Name</th>
                    <th>Course Credit</th>
                    <th>Section</th>
                    <th>Capacity</th>
                    <th>Enrolled Student</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for c in course %}
                <tr>
                    <td class="align-middle">{{ c.semester.season }}</td>
                    <td class="align-middle">{{ c.semester.year }}</td>
                    <td class="align-middle">{{ c.semester.semester }}</td>
                    <td class="align-middle">{{ c.course.course_code }}</td>
                    <td class="align-middle">{{ c.course.course_name }}</td>
                    <td class="align-middle">{{ c.course.course_credit }}</td>
                    <td class="align-middle">{{ c.section }}</td>
                    <td class="align-middle">{{ c.capacity }}</td>
                    <td class="align-middle">{{ c.enrolled_students }}</td>
                    <td ><button class="btnrow">Enroll</button> </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <script type="text/javascript">

            $("#myTable").on('click','.btnrow',function(){

                 var student = $("#student").val();

                 if (student == 'none'){
                     alert("Please Select Student ID!");
                 }

                 var currentRow=$(this).closest("tr");

                 var col5=currentRow.find("td:eq(4)").text();
                 var col6=currentRow.find("td:eq(5)").text();
                 var col7=currentRow.find("td:eq(6)").text();

                 var obj = {
                     course_name: col5,
                     course_credit: col6,
                     section: col7,
                     student: student
                 };

                 console.log(obj);

                 $.ajaxSetup({
                      url: '{% url "advisor:advisor-course-register" %}',
                      global: false,
                      type: "GET",
                      dataType: 'json'
                 });

                 $.ajax({
                     data: obj,

                     beforeSend: function () {
                         return confirm("Are you sure want to enroll "+ col5 +" section "+ col7 +" ?");
                     },

                     success: function (data) {

                         if(data.is_save) {
                             alert("Course Added Successfully!");
                             location.reload();
                         }

                         if(data.is_taken){
                             alert("Student Has Already Registered This Course!");
                         }

                         if (data.credit) {
                             alert("Student Can Not Take Over 18 Credit!");
                         }

                         if (data.enrolled_student) {
                             alert("Section Is Full!");
                         }

                     }

                 });

            });
        </script>

        {% else %}

            <p style="text-align: center">No Course Offer Available</p>

    {% endif %}

{% endblock %}

advisor/templates/advisor.html
{% extends 'index.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'advisor:advisor-view' %}">Advisor Portal</a></li>
    <li class="breadcrumb-item active">My Student List</li>
{% endblock %}

{% block content %}

    {% if students.exists %}
        <table id="myTable" class="table table-striped mb-4" style="margin-top: 22px">

            <thead class="table-inverse">
                <tr>
                    <th>Student ID</th>
                    <th>Student Name</th>
                    <th>Number Of Course</th>
                    <th>Total Credit</th>
                </tr>
            </thead>
            <tbody>

                {% for c in students %}
                    <tr>
                        <td class="align-middle">{{ c.student.user.username }}</td>
                        <td class="align-middle">{{ c.student.user.first_name }} {{ c.student.user.last_name }}</td>
                        <td class="align-middle">{{ c.number_of_course_taken }}</td>
                        <td class="align-middle">{{ c.total_credit_taken }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h4 style="text-align: center">No Student Assign Yet.</h4>
    {% endif %}


{% endblock %}