admin_panel/urls.py
from django.urls import path
from .views import course_offer_view, course_offer_list

app_name = 'admin_panel'

urlpatterns = [

    path('', course_offer_list, name='course-offer-list'),
    path('create', course_offer_view, name='course-offer')

]

advisor/urls.py
from django.urls import path
from .views import advisor_view, course_offer_view, register_view

app_name = 'advisor'

urlpatterns = [

    path('', advisor_view, name='advisor-view'),
    path('advisor/course-offer', course_offer_view, name='advisor-course-offer'),
    path('advisor/course-offer/course-register', register_view, name='advisor-course-register')

]

pre_registration/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from accounts.views import portal, students, advisors

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', portal.home, name='home'),

    path('admin-panel/', include('admin_panel.urls')),

    path('advisor/', include('advisor.urls')),

    path('student/', include('student.urls')),

    path('accounts/signup/', portal.SignUpView.as_view(), name='signup'),

    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),

    path('accounts/signup/advisor/', advisors.AdvisorSignUpView.as_view(), name='advisor_signup'),

    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),

    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view(), name='logout'),

    re_path(r'^accounts/reset/$',
            auth_views.PasswordResetView.as_view(
                template_name='password_reset.html',
                email_template_name='password_reset_email.html',
                subject_template_name='password_reset_subject.txt'
            ),
            name='password_reset'),
    re_path(r'^accounts/reset/done/$',
            auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
            name='password_reset_done'),
    re_path(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
            name='password_reset_confirm'),
    re_path(r'^accounts/reset/complete/$',
            auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
            name='password_reset_complete'),

    re_path(r'^accounts/settings/password/$',
            auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
            name='password_change'),

    re_path(r'^accounts/settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='password_change_done.html'),
            name='password_change_done'),

]

student/urls.py
from django.urls import path
from .views import course_offer_view, student_view, register_view

app_name = 'student'

urlpatterns = [

    path('', student_view, name='student-view'),
    path('student/course-offer', course_offer_view, name='course-offer'),
    path('student/course-register', register_view, name='course-register')

]

templates/corse-detail.html
{% extends 'index.html' %}

{% block breadcrumb %}

{% endblock %}

{% block content %}

    <form method="post" action="students:student-portal">{% csrf_token %}

        <div class="form-group">

    <label for="id_student_id">Student ID:</label>

            <input type="text" name="student_id" class="form-control" id="id_student_id" />

        </div>

    {% include 'includes/form.html' with form=form %}

    <pre><button class="btn btn-primary" type="submit">Save</button></pre>

    </form>



{% endblock %}

templates/course_offer.html
{% extends 'index.html' %}
{% load static %}

{% block stylesheet %}   <link rel="stylesheet" href="{% static 'css/accounts.css' %}">{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item active"><a href="{% url 'admin_panel:course-offer-list' %}">Course Offer List</a></li>
{% endblock %}

{% block content %}
    <h4 style="text-align: center">Create Course Offer</h4>

    <form method="post">{% csrf_token %}

        {% include 'includes/form.html' %}

        <button type="submit" class="btn btn-primary btn-block">Post</button>
    </form>

{% endblock %}

templates/course_offer_list.html
{% extends 'index.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item active"><a href="{% url 'admin_panel:course-offer' %}">Create Course Offer</a></li>
{% endblock %}

{% block content %}
    <h4 style="text-align: center">Course Offer List</h4>

    <table class="table table-striped mb-4" style="margin-top: 22px" border="1" cellspacing="0" cellpadding="2">
            <thead class="table-inverse">
                <tr>
                    <th>Semester</th>
                    <th>Year</th>
                    <th>Course Name</th>
                    <th>Course Code</th>
                    <th>Course Credit</th>
                    <th>Section</th>
                    <th>Capacity</th>
                    <th>Enrolled Students</th>
                </tr>
            </thead>
            <tbody>
            {% for crs in course %}
                <tr>
                    <td class="align-middle">{{ crs.semester.semester }}</td>
                    <td class="align-middle">{{ crs.semester.year }}</td>
                    <td class="align-middle">{{ crs.course.course_name }}</td>
                    <td class="align-middle">{{ crs.course.course_code }}</td>
                    <td class="align-middle">{{ crs.course.course_credit }}</td>
                    <td class="align-middle">{{ crs.section }}</td>
                    <td class="align-middle">{{ crs.capacity }}</td>
                    <td class="align-middle">{{ crs.enrolled_students }}</td>
                </tr>
            {% endfor %}
            </tbody>
    </table>

{% endblock %}

templates/home.html
{% extends 'index.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Student Portal</li>
{% endblock %}

{% block content %}
                <h2>Welcome to the Student Portal! <span class="icon-emo-happy"></span></h2>

    <p class="lead">
        <ul class="lead">If you already have an account, go ahead and <a href="{% url 'login' %}">log in</a>.</ul>

        <ul class="lead">If you are new to Student Portal, get started by creating a
            <a href="{% url 'student_signup' %}">Student Account</a>
            or a <a href="{% url 'advisor_signup' %}">Advisor Account</a>.
        </ul>
    </p>


  <hr style="border: solid 2px black">
        <h3 >What's this about?</h3>

    <p class="lead">
        <ul class="lead">Student confirm their upcoming semester course with section.</ul>
        <ul class="lead">Advisor monitor their students profile.</ul>
        <ul class="lead">Advisor can enroll course of their advising students.</ul>
    </p>

{% endblock content %}

templates/index.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Pre - Registration{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/app.css' %}">

    {% block stylesheet %}{% endblock %}

    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>

  </head>

  <body>
    {% block body %}

        <nav class="navbar sticky-top navbar-expand-md navbar-dark bg-info">
            <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'img/avatar.svg' %}" width="30" height="30" alt="">
            </a>
                <a class="navbar-brand" href="{% url 'home' %}">Pre-Registration</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu"
                        aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="mainMenu">


                    {% if user.is_authenticated %}

                        {% if user.is_student %}
                            <span style="font-style: italic; color: #d0d2a7; margin-left:25%">Logged In As Student</span>
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle dropdown-toggle-split" href="#" id="userMenu" data-toggle="dropdown"
                                        aria-haspopup="true" aria-expanded="false">{{ user.first_name}} {{ user.last_name }}
                                    <span class="sr-only">Toggle Dropdown</span>
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                        <a class="dropdown-item" href="{% url 'student:course-offer' %}">Pre Enroll Course</a>
                                        <a class="dropdown-item" href="{% url 'student:student-view' %}">Pre Registered Course</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                                    </div>
                                </li>
                            </ul>

                        {% elif user.is_advisor %}

                            <span style="font-style: italic; color: #d0d2a7; margin-left:25%">Logged In As Advisor</span>

                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                                        aria-haspopup="true" aria-expanded="false">{{ user.first_name}} {{ user.last_name }}</a>

                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                        <a class="dropdown-item" href="{% url 'advisor:advisor-view' %}">My Student List</a>
                                        <a class="dropdown-item" href="{% url 'advisor:advisor-course-offer' %}">Enroll Student Course</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                                    </div>
                                </li>
                            </ul>

                        {% else %}
                            <form class="form-inline ml-auto">
                            <a href="{% url 'login' %}" class="btn btn-outline-dark ml-2">Log in</a>
                            <a href="{% url 'signup' %}" class="btn btn-outline-dark ml-2">Sign up</a>
                        </form>


                        {% endif %}

                    {% else %}

                        <form class="form-inline ml-auto">
                            <a href="{% url 'login' %}" class="btn btn-outline-dark ml-2">Log in</a>
                            <a href="{% url 'signup' %}" class="btn btn-outline-dark ml-2">Sign up</a>
                        </form>

                    {% endif %}
                </div>
            </div>
        </nav>

        <div class="container">

            <ol class="breadcrumb my-4">
                {% block breadcrumb %}

                {% endblock %}
            </ol>

            {% block content %}

            {% endblock %}

        </div>

    {% endblock body %}


    <!--Footer-->
    <footer class="page-footer font-small indigo pt-0">
        <!--Copyright-->
        <div class="footer-copyright py-3 text-center">
            © 2018 Copyright:
            <a href="https://www.facebook.com/rkn.tss.9"> Rasel.me </a>
        </div>
        <!--/Copyright-->

    </footer>
    <!--/Footer-->

    <script src="{% static 'js/popper.min.js' %}"></script>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block javascript %}{% endblock %}


  </body>
</html>

templates/login.html
{% extends 'index.html' %}

{% block title %}Log in to Student Portal{% endblock %}

{% block breadcrumb %}

    <li class="breadcrumb-item"><a href="{% url 'home' %}">Student Portal</a></li>
    <li class="breadcrumb-item active">Log In</li>

{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Log in</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          New to Job Boards? <a href="{% url 'signup' %}">Sign up</a>
        </div>
      </div>
      <div class="text-center py-2">
        <small>
          <a href="{% url 'password_reset' %}" class="text-muted">Forgot your password?</a>
        </small>
      </div>
    </div>
  </div>
{% endblock %}

templates/password_change.html
{% extends 'index.html' %}

{% block title %}Change password{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Change password</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Change password</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/password_change_done.html
{% extends 'index.html' %}

{% block title %}Change password successful{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'password_change' %}">Change password</a></li>
  <li class="breadcrumb-item active">Success</li>
{% endblock %}

{% block content %}
  <div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed!
  </div>
  <a href="{% url 'home' %}" class="btn btn-secondary">Return to home page</a>
{% endblock %}

templates/password_reset.html
{% extends 'index.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/password_reset_complete.html
{% extends 'index.html' %}

{% block title %}Password changed!{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Password changed!</h3>
          <div class="alert alert-success" role="alert">
            You have successfully changed your password! You may now proceed to log in.
          </div>
          <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/password_reset_confirm.html
{% extends 'index.html' %}

{% block title %}
  {% if validlink %}
    Change password for {{ form.user.username }}
  {% else %}
    Reset your password
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-success btn-block">Change password</button>
            </form>
          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/password_reset_done.html
{% extends 'index.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
          <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Job Boards username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL in a new browser window instead.

If you've received this mail in error, it's likely that another user entered your email address by mistake while trying
to reset a password. If you didn't initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The Django Boards Team